Repository mkhoshkam/orderbook, pull requests merged in 2025-06, with the labels that each got.

#2 feat: implement orderbook functionality
  engine/orderbook.go
  engine/orderbook_test.go
Labels: feature

#3 feat: implement high-performance order matching engine
  engine/engine.go
  engine/engine_test.go
  engine/types.go
Labels: feature

#4 test: reduce concurrency in order processing tests
  engine/engine_test.go
Labels: documentation

#6 Add benchmark tests for orderbook
  engine/benchmark_orderbook_test.go
Labels: test

#9 feat: add configuration for Go linting and formatting
  .github/workflows/lint.yml
  .golangci.yml
  .prettierignore
  .prettierrc
  Makefile
  README.md
  engine/benchmark_orderbook_test.go
  engine/orderbook_test.go
  examples/main.go
Labels: documentation, feature
